---
# Source: applications/templates/namespaces.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: hello
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
# Source: applications/templates/namespaces.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: hello
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
# Source: applications/templates/helm-guestbook.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: hello
    server: https://037DCF9DE4D0767C4AE82970E630E377.gr7.us-east-1.eks.amazonaws.com 
  project: default
  source:
    path: deploy/helm/goodbye-kubernetes
    repoURL: https://github.com/JasonKAls/goodbye-kubernetes
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
---
# Source: applications/templates/helm-guestbook.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: hello
    server: https://037DCF9DE4D0767C4AE82970E630E377.gr7.us-east-1.eks.amazonaws.com 
  project: default
  source:
    path: deploy/helm/hello-kubernetes
    repoURL: https://github.com/JasonKAls/hello-kubernetes
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
